spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/app_db?useUnicode=true&characterEncoding=UTF-8
    username: db_user
    password: db_user_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: false

  encryption:
    jwt:
      secret-key: A=D-_EJdaC-bJ-PKMJO-1950as!
      lifetime: 604800

logging:
  level:
    org.springframework.boot.autoconfigure.sql.init: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE