CREATE DATABASE IF NOT EXISTS app_db
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'db_user'@'%' IDENTIFIED BY 'db_user_password';
GRANT ALL PRIVILEGES ON app_db.* TO 'db_user'@'%';

FLUSH PRIVILEGES;